### ISSUE TITLE
New APIs: HikesClient.CreateHike(hike, handler) and  HikesClient.UpdateHike(hike, handler)

### ISSUE THREAD

**Issue by skipit** [codepath-nomadic/nomadic#24]
Just pushed the stubs to my branch. @ skipit/GoOnAHikeFragment

Git# d83bd17f83d30e00eb6318574bfa21249e0190c3

**Comment by aurambaj** [comment]
done the first version. Photos are still hardcoded in there

**Comment by aurambaj** [comment]
for the update we don't have a way to test yet do we?

**Comment by skipit** [comment]
I will work for a couple of hours now... will see if we can get it up.
