### ISSUE TITLE
New APIs: Hike.updateInvites(ArrayList<PArseUser> users)

### ISSUE THREAD

**Issue by skipit** [codepath-nomadic/nomadic#25]
Just pushed the stubs to my branch. @ skipit/GoOnAHikeFragment

Git# d83bd17f83d30e00eb6318574bfa21249e0190c3

**Comment by skipit** [comment]
Jean did you do this as well ?

**Comment by aurambaj** [comment]
ooops no missed that one, I'll do it soon

**Comment by aurambaj** [comment]
v1 implemented but we should review the hike create flow, the current design is improper for async.
