### ISSUE TITLE
Parse: Hike Object not returning Values properly

### ISSUE THREAD

**Issue by skipit** [codepath-nomadic/nomadic#26]
Jean.

If you refer to skipit/GoOnAHikeFragment. 

HikeDetailActivity.initializeViewHandles(), I have code commented out to fill in the views with information from hike, however I am getting null pointer exceptions on getting Values. Can you take a look.

Refer Git# bfa038e9b7165b624c659031f9c617d622ce5ef8

-- Pavan

**Comment by aurambaj** [comment]
You can create a pull request and comment on the line. It makes stuff simpler to review.

created/updated are already in the ParseObject. I don't think we should redefine new getter/setter. Else where do you get the NPE? is that for some values that are define in the parse object (I mean checking via parse web UI)? In any case the activity should probably check for NPE to be robust.

**Comment by skipit** [comment]
Well if I cannot get hike.createdBy, then what do I do in HikeDetail Activity... should I bail out and dismiss() the current ACtivity. 

I merged my code for now, will do it next time onwards.

**Comment by aurambaj** [comment]
hum weird for the createdBy

else, getCreatedAt is already in ParseObject so we shouldn't redefine. I beleive the setter is not available because the framewrok is the one setting it. I haven't check in details though. So I'd removed those

**Comment by skipit** [comment]
ok. I can remove setCreatedAt. What about updatedAt

**Comment by aurambaj** [comment]
same

**Comment by skipit** [comment]
Ok. WIll remove both.

**Comment by skipit** [comment]
k. I removed it.... 

Looks like currentHike.getCreatedBy().getUsername() gives an error as follows

java.lang.IllegalStateException: ParseObject has no data for 'username'. Call fetchIfNeeded() to get the data.

However currentHike.getCreatedBy() returns a ParseObject

**Comment by aurambaj** [comment]
Sounds like it's ok now. I got the whole flow, create hike, notification, open detail hike working.

**Comment by skipit** [comment]
Thanks Jean... Did you push to master ? or did you do on my branch ?
