### ISSUE TITLE
Pass Bundle to HikeDetailActivity

### ISSUE THREAD

**Issue by skipit** [codepath-nomadic/nomadic#27]
Hi Perk.

Can you please merge to master code where you send a Bundle to HikeDetailActivity. 

This is what I need in the bundle.

 Bundle bundle = new Bundle();
 bundle.putString(Constants.HIKE_ID, currentHike.getObjectId());
  i.putExtras(bundle);
  startActivityForResult(i, Constants.triggerHikeDetailCallId); 

I have updated code to handle these. Want to test it out. 

-- Pavan.

**Comment by perklun** [comment]
Should the constant be triggerCRUDHikeCreateCallId instead?

**Comment by perklun** [comment]
Looks like i can't start an activity with a constant.

Will this work for you?

                Bundle bundle = new Bundle();
                bundle.putString(Constants.HIKE_ID, hike.getObjectId());
                Intent i = new Intent(getContext(), HikeDetailActivity.class);
                getContext().startActivity(i, bundle);

**Comment by perklun** [comment]
Just pushed the code, let me know if it works

**Comment by skipit** [comment]
Looks like I get the intent. However I think you are not using the Hikes From Parse... so I get a null Object ID.

**Comment by perklun** [comment]
applied a fix. I check in debugger. it should not be null

**Comment by skipit** [comment]
Great will try it out... now.
