### ISSUE TITLE
Parse: Hike committed column not found

### ISSUE THREAD

**Issue by skipit** [codepath-nomadic/nomadic#28]
Hi Jean,

I looked at the database online and I dont see the "committed" column for hike. 

Pavan

**Comment by aurambaj** [comment]
that's probably because it wasn't set (at least when the table was created). I suppose you've set it now and it's not appearing? If so, I should add it in createHike fct and probably recreate the table.

**Comment by skipit** [comment]
Ok. I cannot create hike now, as I dont have the HikesClient.createHike(hike, handler) available. We can wait till that is there.

**Comment by skipit** [comment]
CRUDHikeActivity.handleBtCRUDHike() is where I would set the flag... yes I did not set it yet.

**Comment by aurambaj** [comment]
fixed column is there now
